--JOIN

/*
INNER JOIN

EQUI 동등조인 =
SEMI 세미조인 IN, BETWEEN
ANTI 안티조인 !=
SELF 셀프조인 같은 테이블을 조인
*/

-- EQUI JOIN
SELECT EMPLOYEE_ID,EMP_NAME,DEPARTMENT_ID FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.EMP_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT a.EMPLOYEE_ID, a.EMP_NAME, b.DEPARTMENT_NAME, b.DEPARTMENT_ID
FROM EMPLOYEES a, DEPARTMENTS b
WHERE a.DEPARTMENT_ID = b.DEPARTMENT_ID;


/*
OUTER JOIN

LEFT OUTER
RIGHT OUTER
FULL OUTER
*/