/*서브쿼리 : SQL문 안에 하나이상의 SQL문이 들어있는 경우

SELECT 일반서브쿼리
FROM 인라인 뷰
WHERE 중첩 서브쿼리
*/

/*월급이 5천~만 사이의 사번, 이름, 월급 부서명*/
SELECT A.EMPLOYEE_ID, A.EMP_NAME, A.SALARY, B.DEPARTMENT_NAME
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID = b.department_id AND A.SALARY BETWEEN 5000 AND 10000;

SELECT A.EMPLOYEE_ID, A.EMP_NAME, A.SALARY, B.DEPARTMENT_NAME
FROM (
    SELECT EMPLOYEE_ID, EMP_NAME, SALARY, DEPARTMENT_ID 
    FROM EMPLOYEES 
    WHERE SALARY BETWEEN 5000 AND 10000) A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID; -- 인라인 뷰

SELECT COUNT(*)
FROM EMPLOYEES
WHERE SALARY>=(SELECT AVG(SALARY) FROM EMPLOYEES);

COMMIT;
ROLLBACK;
--연관성 없는 서브쿼리
UPDATE EMPLOYEES
SET SALARY=(SELECT AVG(SALARY) FROM EMPLOYEES);

DELETE EMPLOYEES
WHERE SALARY<=(SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT COUNT(*)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE PARENT_ID IS NULL);