SELECT EMP_NAME , SUBSTR(TO_CHAR(HIRE_DATE,'yyyy-mm-dd'),1,4) FROM EMPLOYEES;
-- 입사연도별 인원수 -TO_CHAR, SUBSTR, GROUP BY

SELECT SUBSTR(TO_CHAR(HIRE_DATE,'yyyy-mm-dd'),1,4) 입사년도, COUNT(*) 인원수
FROM EMPLOYEES 
group by SUBSTR(TO_CHAR(HIRE_DATE,'yyyy-mm-dd'),1,4)
ORDER BY 입사년도;

-- 사원번호, 이름, 직위명 107명 모두
SELECT a.EMPLOYEE_ID AS 사원번호, a.EMP_NAME AS 이름, b.JOB_TITLE AS 직위명
FROM EMPLOYEES a, JOBS b
WHERE a.JOB_ID = b.JOB_ID (+)
ORDER BY 사원번호;

-- 부서명, 부서장이름, 부서원숫자
SELECT A.DEPARTMENT_NAME AS 부서명, B.EMP_NAME 부서장, COUNT(C.EMP_NAME) AS 부서원수
FROM DEPARTMENTS A, EMPLOYEES B, EMPLOYEES C
WHERE B.EMPLOYEE_ID = A.MANAGER_ID AND A.DEPARTMENT_ID = C.DEPARTMENT_ID
GROUP BY A.DEPARTMENT_NAME, B.EMP_NAME;

-- 부서명, 부서장이름, 평균 월급이상인 부서원숫자
SELECT A.DEPARTMENT_NAME AS 부서명, B.EMP_NAME 부서장, COUNT(C.EMP_NAME) AS 부서원수
FROM DEPARTMENTS A, 
            EMPLOYEES B, 
            (SELECT EMP_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE SALARY>=(SELECT AVG(SALARY) FROM EMPLOYEES)) C
WHERE B.EMPLOYEE_ID = A.MANAGER_ID AND A.DEPARTMENT_ID = C.DEPARTMENT_ID 
GROUP BY A.DEPARTMENT_NAME, B.EMP_NAME;

-- 고객별 상품별 매입액 : 고객명, 상품명, 매입총액
SELECT B.CUST_NAME, C.PROD_NAME, SUM(A.AMOUNT_SOLD)
FROM SALES A, CUSTOMERS B, PRODUCTS C
WHERE A.CUST_ID=B.CUST_ID AND A.PROD_ID = C.PROD_ID
GROUP BY B.CUST_NAME, C.PROD_NAME
ORDER BY B.CUST_NAME;

-- 고객명,  구매한 상품명
SELECT B.CUST_NAME, C.PROD_NAME
FROM    SALES A, 
            CUSTOMERS B, 
            PRODUCTS C
WHERE A.CUST_ID = B.CUST_ID AND A.PROD_ID = C.PROD_ID
ORDER BY B.CUST_NAME;

-- 상품별 매출액
SELECT PROD_NAME, SUM(AMOUNT_SOLD)
FROM PRODUCTS C, SALES A
WHERE A.PROD_ID = C.PROD_ID
GROUP BY PROD_NAME;

-- 사장의 직속부하인 직원이 매니저인 사원 숫자
-- 직속부하명, 직원숫자
SELECT A.EMP_NAME 사장직속부하, COUNT(B.EMP_NAME) 직원수
FROM EMPLOYEES A, (SELECT EMP_NAME, MANAGER_ID FROM EMPLOYEES) B
WHERE A.MANAGER_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL) AND A.EMPLOYEE_ID = B.MANAGER_ID
GROUP BY A.EMP_NAME
ORDER BY 사장직속부하;

SELECT A.EMP_NAME 사장직속부하, COUNT(*) 직원수
FROM EMPLOYEES A, EMPLOYEES B
WHERE A.MANAGER_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL) AND A.EMPLOYEE_ID = B.MANAGER_ID
GROUP BY A.EMP_NAME
ORDER BY 사장직속부하;