SELECT EMP_NAME , SUBSTR(TO_CHAR(HIRE_DATE,'yyyy-mm-dd'),1,4) FROM EMPLOYEES;
-- 입사연도별 인원수 -TO_CHAR, SUBSTR, GROUP BY

SELECT SUBSTR(TO_CHAR(HIRE_DATE,'yyyy-mm-dd'),1,4) 입사년도, COUNT(*) 인원수
FROM EMPLOYEES 
group by SUBSTR(TO_CHAR(HIRE_DATE,'yyyy-mm-dd'),1,4)
ORDER BY 입사년도;

-- 사원번호, 이름, 직위명 107명 모두
SELECT a.EMPLOYEE_ID AS 사원번호, a.EMP_NAME AS 이름, b.JOB_TITLE AS 직위명
FROM EMPLOYEES a, JOBS b
WHERE a.JOB_ID = b.JOB_ID (+)
ORDER BY 사원번호;

-- 부서명, 부서장이름, 부서원숫자
SELECT A.DEPARTMENT_NAME AS 부서명, B.EMP_NAME 부서장, COUNT(C.EMP_NAME) AS 부서원수
FROM DEPARTMENTS A, EMPLOYEES B, EMPLOYEES C
WHERE B.EMPLOYEE_ID = A.MANAGER_ID AND A.DEPARTMENT_ID = C.DEPARTMENT_ID
GROUP BY A.DEPARTMENT_NAME, B.EMP_NAME;
