--BUITIN FUNCTION 변환

-- ★TO_CHAR(숫자/날짜) -> 문자열로 변경
-- TO_NUMBER(문자열) -> 숫자로 변경

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YY.MM.DD') FROM DUAL;
SELECT TO_CHAR(SYSTIMESTAMP,'YY-MM-DD HH:MI:SS') FROM DUAL;

SELECT TO_NUMBER('1234') FROM DUAL;
INSERT INTO EMPLOYEES VALUES(TO_NUMBER('1234'), 'PARK', '44445555');

