/*기본 집계함수
COUNT : 레코드 갯수
SUM(숫자칼럼명) : 칼럼값의 합계
AVG : 평균
MIN / MAX : 최소 최대
VARIANCE / STDDEV : 분산도 / 표준편차

DISTINCT : 중복 제거
ORDER BY 컬럼명1, ......, 컬럼명n
AEC / DESC : 오름차순 / 내림차순
*/

SELECT COUNT(*) FROM SALES;
SELECT COUNT(EMP_NAME), COUNT(MANAGER_ID) FROM EMPLOYEES; -- NULL은 포함 안됨(*제외)

CREATE TABLE STD(NAME VARCHAR2(12), MOBILE VARCHAR2(12));
INSERT INTO STD VALUES('John','44445555');
inserT INTO STD VALUES(NULL,NULL);
SELECT COUNT(*) FROM STD;
SELECT COUNT(NAME) FROM STD;

SELECT SUM(SALARY) FROM EMPLOYEES;

SELECT TO_CHAR(AVG(SALARY),'9999.99') FROM EMPLOYEES;

SELECT MIN(SALARY), MAX(SALARY) FROM EMPLOYEES;

SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY ASC;
SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT EMP_NAME FROM EMPLOYEES ORDER BY EMP_NAME DESC;
SELECT SALARY, EMP_NAME FROM EMPLOYEES ORDER BY SALARY, EMP_NAME DESC;