/* PLSQL 제어문

IF문

<조건하나>
IF 조건문 THEN
    실행문;
END IF;

<조건 N개>
IF 조건1 THEN
    조건 처리1;
ELSIF 조건2 THEN
    조건 처리 2;
    .......
ELSE
    조건 처리 N;
END IF;
*/

DECLARE
    VN_SALARY EMPLOYEES.SALARY%TYPE;
    VN_DID departments.department_id%TYPE;
BEGIN
    SELECT SALARY INTO VN_SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 90 AND ROWNUM=1;
    
    DBMS_OUTPUT.PUT_LINE(VN_SALARY);
    
    IF VN_SALARY BETWEEN 1 AND 3000 THEN
        DBMS_OUTPUT.PUT_LINE('낮음');
    ELSIF VN_SALARY BETWEEN 3001 AND 6000 THEN
        DBMS_OUTPUT.PUT_LINE('중간');
    ELSIF VN_SALARY BETWEEN 6001 AND 10000 THEN
        DBMS_OUTPUT.PUT_LINE('높음');
    ELSE
        DBMS_OUTPUT.PUT_LINE('최상위');
    END IF;
END;
/

/* 월급이 10000불인 사람의 이름과 부서명*/
DECLARE
    VN_NAME EMPLOYEES.EMP_NAME%TYPE;
    VN_DPNAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    SELECT A.EMP_NAME,  B.DEPARTMENT_NAME
    INTO VN_NAME, VN_DPNAME
    FROM EMPLOYEES A, DEPARTMENTS B
    WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID AND A.SALARY=10000 AND ROWNUM=1;
    DBMS_OUTPUT.PUT_LINE(VN_NAME||' - '||VN_DPNAME);
END;
/