/* CURSOR : SQL실행 결과가 저장된 메모리의 특별한 지역/위치
                (SELECT)
                
묵시적(implicit) 커서 : 자동으로 생성되는 커서
SQL%FOUND : SELECT 결과로 1개 이상이 조회되면 TRUE
SQL%NOTFOUND : SELECT 결과가 없으면 TRUE
SQL%ROWCOUNT : SELECT시 나온 집합의 로우 수 반환
SQL%ISOPEN

명시적(explicit) 커서 : PL/SQL코드로 의도적으로 만든 커서

1. 커서 언언
2. 커서 열기 : OPEN
3. 커서에 저장된 데이터 사용 : FETCH
4. 커서 닫기
*/

CREATE TABLE MEMBER(
    NAME VARCHAR2(80),
    MOBLIE VARCHAR2(32)
);
SELECT ROWNUM, ROWID /*묵시적*/ , NAME, MOBLIE FROM MEMBER;

DECLARE
    VS_NAME EMPLOYEES.EMP_NAME%TYPE;
BEGIN
    SELECT EMP_NAME INTO VS_NAME FROM EMPLOYEES
    WHERE MANAGER_ID IS NULL;
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE(VS_NAME);
    ELSE
        DBMS_OUTPUT.PUT_LINE('CANNOT FOUND');
    END IF;
END;
/

DECLARE
    VS_NAME EMPLOYEES.EMP_NAME%TYPE;
BEGIN
    SELECT EMP_NAME INTO VS_NAME FROM EMPLOYEES
    WHERE MANAGER_ID =10000; -- ERROR
    DBMS_OUTPUT.PUT_LINE(VS_NAME);
    
    EXCEPTION WHEN OTHERS THEN
        IF SQL%NOTFOUND THEN
            DBMS_OUTPUT.PUT_LINE('CANNOT FOUND');
        END IF;
END;
/


DECLARE
    VS_NAME EMPLOYEES.EMP_NAME%TYPE;
BEGIN
    SELECT EMP_NAME INTO VS_NAME FROM EMPLOYEES
    WHERE MANAGER_ID IS NULL;
    DBMS_OUTPUT.PUT_LINE(VS_NAME||', 인원수['||SQL%ROWCOUNT||'}');
    
    EXCEPTION WHEN OTHERS THEN
        IF SQL%NOTFOUND THEN
            DBMS_OUTPUT.PUT_LINE('CANNOT FOUND');
        END IF;
END;
/


DECLARE
    CURSOR C1(a number, b number) -- 1. 커서 선언
    IS
        SELECT EMP_NAME FROM EMPLOYEES WHERE SALARY BETWEEN a and b;
    VS_NAME EMPLOYEES.EMP_NAME%TYPE;
BEGIN
    OPEN C1(0,3000) ; -- 2. 커서 열기
    LOOP
        FETCH C1 INTO VS_NAME; -- 3. 데이터 사용
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(VS_NAME);
    END LOOP;
    CLOSE C1; -- 4. 커서 닫기
END;
/

DECLARE
    CURSOR C1(x number) -- 1. 커서 선언
    IS
        SELECT EMP_NAME,DEPARTMENT_ID FROM EMPLOYEES WHERE MANAGER_ID = x;
    VS_NAME EMPLOYEES.EMP_NAME%TYPE;
    VS_DID EMPLOYEES.DEPARTMENT_ID%TYPE;
BEGIN
    OPEN C1(100) ; -- 2. 커서 열기
    LOOP
        FETCH C1 INTO VS_NAME, VS_DID; -- 3. 데이터 사용
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(VS_NAME);
    END LOOP;
    CLOSE C1; -- 4. 커서 닫기
END;
/

-- CURSOR VER2
DECLARE
    CURSOR C1(x number) -- 1. 커서 선언
    IS
        SELECT EMP_NAME,DEPARTMENT_ID FROM EMPLOYEES WHERE MANAGER_ID = x;
    VS_NAME EMPLOYEES.EMP_NAME%TYPE;
    VS_DID EMPLOYEES.DEPARTMENT_ID%TYPE;
BEGIN
    FOR REC IN C1(100)
    LOOP
        DBMS_OUTPUT.PUT_LINE(REC.EMP_NAME||','||REC.DEPARTMENT_ID);
    END LOOP;
END;
/

-- CURSOR VER3
DECLARE
BEGIN
    FOR REC IN (SELECT EMP_NAME, DEPARTMENT_ID
                FROM EMPLOYEES
                WHERE MANAGER_ID=100)
    LOOP
        DBMS_OUTPUT.PUT_LINE(REC.EMP_NAME||','||REC.DEPARTMENT_ID);
    END LOOP;
END;
/